; Generated by phpVMS for <?php echo SITE_NAME ?> on <?php echo date('m-d-Y') ?>

[ACARS_CONFIG]
ADDRESS=<?php echo url('/fsfk/acars'); ?>
PORT=80
USER=
PASSWORD=

POSITIONREPORT=2
POSITIONREPORT_EX=10

LIVEWATCH=<?php echo url('/fsfk/livewatch'); ?>
LIVEWATCHREFRESH=60